groups:
  - name: too_many_request_count_total
    rules:
    - alert: TooManyReq
      expr: request_count_total > 1
      for: 1s
      labels:
        severity: 'critical'
      annotations:
        summary: "request_count_total is too over!"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has over 1 for more than 1 sec."
        username: "@channel"
    - alert: InstanceDown
      # Condition for alerting
      expr: up == 0
      for: 1s
      # Annotation - additional informational labels to store more information
      # Labels - additional labels to be attached to the alert
      labels:
        severity: 'critical'
      annotations:
        title: 'Instance {{ $labels.instance }} down'
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 second.'