kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    registry: 140.112.31.162:80
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    username:
      from_secret: harbor_username
    password:
      from_secret: harbor_password

trigger:
  branch:
  - main
  event:
    include:
    - push
    - pull_request
    - rollback

steps:
- name: backend-test
  pull: if-not-exists
  image: golang:latest
  # The commands are executed inside the root directory of the git repository
  commands:
  - cd backend/app
  - go mod download
  - make test

- name: build-image
  <<: *x-build-docker-image
  settings:
    repo: 140.112.31.162:80/test
    dockerfile: backend/app/Dockerfile
    context: backend/app
  depends_on:
    - backend-test

- name: notify
  image: plugins/slack
  settings:
    webhook:
      # specified on the Drone server web interface
      from_secret: webhook
  when:
    status:
    - failure
    - success
  depends_on:
    - backend-test
    