global:
  resolve_timeout: 2h # 未收到標記告警通知，等待 timeout 時間之後事件標記為 resolve

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 10s # 重複發送告警的間隔時間
  repeat_interval: 1h
  receiver: 'slack' # default receiver

receivers:
  - name: 'slack'
    slack_configs:
      # webhook URL for the "incoming webhook" app in channel "#alert-test"
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#alert-test"
        send_resolved: true
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}